### ISSUE TITLE
Changes to Whitelist username creation

### ISSUE THREAD

**Issue by SteveyO** [bsalinas/huejs#1]
Hi Ben,

As there have been no commits in 3+ years I assume you don't plan to actively maintain this anymore?

If you do plan to make changes I should mention that in a few months time we will be changing the way usernames are created on the bridge.  Custom whitelist usernames will no longer be allowed and the bridge randomly generated username must be used instead.  Please see below link for more information:
http://www.developers.meethue.com/documentation/important-whitelist-changes

I see from your huejs.js file you are posting the username in your POST body.  This will start failing in February 2016 and it will no longer be able to connect to a bridge with a custom username.

Thanks
Steve (Philips Hue Dev Support).

**Comment by bsalinas** [comment]
Hi Steve,
Thanks for the information. I am not actively maintaining the repo, but I
will add a note to the readme in case anyone tries to use it and runs into
a problem.

Thanks!

**Comment by SteveyO** [comment]
Great! Thanks Ben.  A note in the readme will certainly help and will be appreciated!
Steve

**Comment by picassoruiz** [comment]
Hi Ben, 
I was checking Your repo and it's working still like a charm for manipulating the lights 👍 
I created the user directly in the Philips Hue CLIP API Debugger.

cheers Pawel
